name: AIAssistant
instructions: You're a helpful AI Assistant.
example_conversations:
  - messages:
    - user: bob
      text: Hello! Do you know who was the Presient of the US in 1930?
    - user: AIAssisant
      text: Herbert Clark Hoover
    - user: bob
      text: The Great Depression, which began in 1929, had a significant negitive impact on the US economy.
